version: '3.7'

services:
  gpg:
    image: postgres:12-alpine
    hostname: gpg
    container_name: gpg
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: gophkeeper
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      outside-network:
        aliases:
          - "gpg"
      backend-network: { }
networks:
  backend-network:
  outside-network:
    external: true
    name: "primary-network"

volumes:
  pg-data:
